const puppeteer = require('puppeteer');
const fs = require('fs');

// --- CONFIGURATION ---
const HOME_URL = 'https://cpq.agcocorp.com/agco/customer/en_gb/configurator';
const OUTPUT_FILE = 'Full_CPQ_Data_CS.txt';
const TIMEOUT_MS = 120000; // 2 Minutes (Slow Server Protection)

// --- SELECTORS ---
const SELECTORS = {
    // Home Page Brand Cards
    brandCard: '.sub-brand-card, .brand-card',

    // Product Grid Items (The tiles you click to see details)
    gridItem: '.product-item, .category-tile, .card, div[class*="tile"], div[class*="product"]',

    // Data on the Product Page
    title: 'h1',
    desc: '.description, .product-description, #description, .marketing-text',
    specs: '.specifications, table.tech-specs',

    // Loading Spinner
    loader: '.loader, .spinner, .mat-spinner'
};

(async () => {
    console.log("=================================================");
    console.log("   SAP CPQ 'GRAND TOUR' SCRAPER - ADMIN: CS");
    console.log("=================================================");

    // Initialize Output File
    fs.writeFileSync(OUTPUT_FILE, "SAP CPQ DATA EXPORT - GENERATED BY PUPPETEER\n============================================\n\n");

    const browser = await puppeteer.launch({
        headless: false, // Visible for debugging
        defaultViewport: null,
        args: ['--start-maximized']
    });

    const page = await browser.newPage();

    // 1. DEFINE BRANDS TO VISIT
    // We use keywords to find the right cards on the home page
    const BRAND_KEYWORDS = ["Massey Ferguson", "Fendt", "Valtra"];

    for (const brandName of BRAND_KEYWORDS) {
        console.log(`\n\n>>> PREPARING TO SCRAPE BRAND: ${brandName.toUpperCase()}`);

        // A. Go to Home Page (Reset State)
        await page.goto(HOME_URL, { waitUntil: 'domcontentloaded', timeout: TIMEOUT_MS });
        await waitForSpinner(page);

        // B. Find and Click the Brand Card
        const brandClicked = await clickBrandByText(page, brandName);
        if (!brandClicked) {
            console.error(`    !!! Could not find brand card for "${brandName}". Skipping.`);
            continue;
        }

        // C. Wait for Catalog to Load
        console.log("    ...Entering Catalog...");
        await new Promise(r => setTimeout(r, 5000)); // Allow transition
        await waitForSpinner(page);

        // D. EXECUTE "CLICK AND SCRAPE" LOOP
        await scrapeCatalogGrid(page, brandName);
    }

    console.log("\n=================================================");
    console.log(`COMPLETE! All data saved to: ${OUTPUT_FILE}`);
    console.log("Please upload this file to the chat.");
    await browser.close();
})();


// --- CORE FUNCTION: Scrape the Grid ---
async function scrapeCatalogGrid(page, brandContext) {
    // 1. Count Items
    await page.waitForSelector(SELECTORS.gridItem, { timeout: 20000 }).catch(() => console.log("    (No items found or timeout)"));

    const itemCount = await page.evaluate((sel) => document.querySelectorAll(sel).length, SELECTORS.gridItem);
    console.log(`    Found ${itemCount} items for ${brandContext}.`);

    if (itemCount === 0) return;

    // 2. Loop Items
    for (let i = 0; i < itemCount; i++) {
        // Re-select because DOM refreshes
        const items = await page.$$(SELECTORS.gridItem);
        const item = items[i];

        if (!item) continue;

        try {
            // Get Name (for log)
            const name = await page.evaluate(el => el.innerText.split('\n')[0], item);
            console.log(`    [${i+1}/${itemCount}] Processing: "${name}"`);

            // CLICK
            await item.click();

            // WAIT for Detail Page (Look for H1 title)
            try {
                await page.waitForSelector('h1', { timeout: 15000 });
            } catch(e) {
                console.log("    (Warning: No Title found, scraping whatever is there...)");
            }

            // SCRAPE TEXT
            const data = await page.evaluate((sel) => {
                const clean = (text) => text ? text.replace(/\s+/g, ' ').trim() : "N/A";
                return {
                    title: clean(document.querySelector(sel.title)?.innerText),
                    desc: clean(document.querySelector(sel.desc)?.innerText),
                    specs: clean(document.querySelector(sel.specs)?.innerText)
                };
            }, SELECTORS);

            // APPEND TO FILE
            const entry = `
--------------------------------------------------
BRAND: ${brandContext}
PRODUCT: ${data.title}
ADMIN: Chirag Singhal
TIMESTAMP: ${new Date().toISOString()}

DESCRIPTION:
${data.desc}

SPECIFICATIONS:
${data.specs}
--------------------------------------------------
`;
            fs.appendFileSync(OUTPUT_FILE, entry);
            console.log(`    >>> Saved "${data.title}"`);

            // GO BACK
            await page.goBack({ waitUntil: 'domcontentloaded' });
            await waitForSpinner(page);
            await new Promise(r => setTimeout(r, 2000)); // Small pause for grid re-render

        } catch (err) {
            console.error(`    !!! Error on item ${i+1}: ${err.message}`);
            // Attempt recovery
            if (!page.url().includes('wholegoods')) {
                await page.goBack();
            }
        }
    }
}


// --- HELPER: Click Brand on Home Page ---
async function clickBrandByText(page, text) {
    return await page.evaluate((sel, textToFind) => {
        const cards = Array.from(document.querySelectorAll(sel));
        const target = cards.find(card => card.innerText.includes(textToFind));
        if (target) {
            target.click();
            return true;
        }
        return false;
    }, SELECTORS.brandCard, text);
}

// --- HELPER: Wait for Angular Spinner ---
async function waitForSpinner(page) {
    try {
        await page.waitForSelector('.loader', { hidden: true, timeout: 5000 });
    } catch(e) {}
}