const puppeteer = require('puppeteer');
const fs = require('fs');

// --- CONFIGURATION ---
const HOME_URL = 'https://cpq.agcocorp.com/agco/customer/en_gb/configurator';
const OUTPUT_FILE = 'Full_CPQ_Data_CS.txt';

// MAP: Brand Name -> Fallback URL (Used if clicking fails)
const BRAND_MAP = [
    {
        name: "Massey Ferguson",
        directUrl: "https://cpq.agcocorp.com/masseyferguson/customer/en_gb/wholegoods/products"
    },
    {
        name: "Fendt",
        directUrl: "https://cpq.agcocorp.com/fendt/customer/en_gb/wholegoods/products"
    },
    {
        name: "Valtra",
        directUrl: "https://cpq.agcocorp.com/valtra/customer/en_gb/wholegoods/products"
    }
];

// --- SELECTORS ---
const SELECTORS = {
    // Looks for the card OR the image inside it
    brandCard: '.sub-brand-card',

    // Product Grid Items
    gridItem: '.product-item, .category-tile, .card, div[class*="tile"], div[class*="product"]',

    // Data Extraction
    title: 'h1',
    desc: '.description, .product-description, #description, .marketing-text',
    specs: '.specifications, table.tech-specs, .attributes-list',

    // Loading Spinner
    loader: '.loader, .spinner, .mat-spinner'
};

(async () => {
    console.log("=================================================");
    console.log("   SAP CPQ ROBUST SCRAPER (V2) - ADMIN: CS");
    console.log("=================================================");

    fs.writeFileSync(OUTPUT_FILE, "SAP CPQ DATA EXPORT - GENERATED BY PUPPETEER\n============================================\n\n");

    const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: null,
        args: ['--start-maximized']
    });

    const page = await browser.newPage();

    // Set Infinite Timeout for slow connections
    page.setDefaultNavigationTimeout(0);

    for (const brand of BRAND_MAP) {
        console.log(`\n\n>>> PROCESSING BRAND: ${brand.name.toUpperCase()}`);

        let enteredCatalog = false;

        // STEP A: TRY HOME PAGE NAVIGATION (As requested)
        try {
            console.log(`    [1] Navigating to Home Page...`);
            await page.goto(HOME_URL, { waitUntil: 'domcontentloaded' });
            await waitForSpinner(page);

            // Try to find and click the card
            console.log(`    [2] Looking for '${brand.name}' card...`);
            const clicked = await clickBrandSmart(page, brand.name);

            if (clicked) {
                console.log(`    [3] Click successful! Waiting for catalog...`);
                await waitForSpinner(page);
                // Wait for grid to appear
                try {
                    await page.waitForSelector(SELECTORS.gridItem, { timeout: 15000 });
                    enteredCatalog = true;
                } catch(e) {
                    console.log("    (Warning: Clicked, but grid didn't load. Retrying via Direct URL...)");
                }
            } else {
                console.log("    (Could not find clickable card. Switching to Failsafe...)");
            }
        } catch (e) {
            console.log(`    (Home page error: ${e.message})`);
        }

        // STEP B: FAILSAFE (Direct URL)
        if (!enteredCatalog) {
            console.log(`    [FAILSAFE] Force-navigating to Catalog URL...`);
            await page.goto(brand.directUrl, { waitUntil: 'domcontentloaded' });
            await waitForSpinner(page);
        }

        // STEP C: SCRAPE THE CATALOG
        await scrapeCatalogGrid(page, brand.name);
    }

    console.log("\n=================================================");
    console.log(`COMPLETE! All data saved to: ${OUTPUT_FILE}`);
    console.log("Please upload this file to the chat.");
    await browser.close();
})();


// --- SMART CLICKER (Checks Text AND Image Alt) ---
async function clickBrandSmart(page, keyword) {
    return await page.evaluate((sel, key) => {
        const cards = Array.from(document.querySelectorAll(sel));

        const target = cards.find(card => {
            // Check visible text
            const text = card.innerText || "";
            // Check image alt tag (The likely fix)
            const img = card.querySelector('img');
            const alt = img ? img.getAttribute('alt') : "";

            return text.includes(key) || (alt && alt.includes(key));
        });

        if (target) {
            target.click();
            return true;
        }
        return false;
    }, SELECTORS.brandCard, keyword);
}


// --- CORE SCRAPER LOOP ---
async function scrapeCatalogGrid(page, brandContext) {
    console.log(`    [4] Scanning Catalog Grid for ${brandContext}...`);

    // Wait up to 30s for items to appear
    try {
        await page.waitForSelector(SELECTORS.gridItem, { timeout: 30000 });
    } catch(e) {
        console.log(`    !!! No items found for ${brandContext}. Skipping.`);
        return;
    }

    const itemCount = await page.evaluate((sel) => document.querySelectorAll(sel).length, SELECTORS.gridItem);
    console.log(`    >>> Found ${itemCount} products.`);

    for (let i = 0; i < itemCount; i++) {
        // Re-acquire element
        const items = await page.$$(SELECTORS.gridItem);
        const item = items[i];
        if (!item) continue;

        try {
            // Get Name
            let name = await page.evaluate(el => el.innerText.split('\n')[0], item);
            if (!name) name = `Item_${i+1}`;

            console.log(`    [${i+1}/${itemCount}] Scraping: "${name}"`);

            // CLICK
            await item.click();

            // WAIT FOR TITLE (Proof we are on details page)
            try {
                await page.waitForSelector('h1', { timeout: 15000 });
            } catch(e) {
                // Ignore timeout, scrape whatever is there
            }

            // EXTRACT
            const data = await page.evaluate((sel) => {
                const getT = (s) => document.querySelector(s)?.innerText.replace(/\s+/g, ' ').trim() || "N/A";
                return {
                    title: getT(sel.title),
                    desc: getT(sel.desc),
                    specs: getT(sel.specs)
                };
            }, SELECTORS);

            // SAVE
            const entry = `
--------------------------------------------------
BRAND: ${brandContext}
PRODUCT: ${data.title}
ADMIN: Chirag Singhal
TIMESTAMP: ${new Date().toISOString()}

DESCRIPTION:
${data.desc}

SPECIFICATIONS:
${data.specs}
--------------------------------------------------
`;
            fs.appendFileSync(OUTPUT_FILE, entry);

            // BACK
            await page.goBack({ waitUntil: 'domcontentloaded' });
            await waitForSpinner(page);
            await new Promise(r => setTimeout(r, 2000)); // Pause for grid reload

        } catch (err) {
            console.log(`    (Error scraping item ${i+1}: ${err.message})`);
            if (!page.url().includes('wholegoods')) await page.goBack();
        }
    }
}

async function waitForSpinner(page) {
    try {
        await page.waitForSelector('.loader', { hidden: true, timeout: 5000 });
    } catch(e) {}
}